@ControllerWeb_HostAddress = https://localhost:7297
@id = 56

POST {{ControllerWeb_HostAddress}}/register
Content-Type: application/json

{
  "email":"test5@pasit.nl",
  "password":"Test_12345"
}
###

POST {{ControllerWeb_HostAddress}}/login
Content-Type: application/json

{
  "email":"test5@pasit.nl",
  "password":"Test_12345"
}
###

GET {{ControllerWeb_HostAddress}}/brands
Accept: application/json
Authorization: Bearer CfDJ8JrTm5koyVpMrj-2ouRSkkGIz1vnCt68XRZOoLDtv_yi0SC-vGDJNX56JLZ3HMYvQBOHMqzzvj7h8kYDrtW3nCVgys29z1dNSSjWKOLeEzjlrYWMGydHPQrwDZBB79BIEwKuh5ADk-AkW6_CnHtusApkNCj2t_Ps47K8coNZYJ8i2AiiAJMoKS58z2tNFg3vOF-criCQ_Sxkonh-GII2tmFrEJPepQAcqt0CGMx7jEyCfUPzd9OcddvOGPvJ2dYmrn9v0k8LRC7NfPGlNQDDeXZ8qm-MvMXrgQN6hNWV3JGnNNn-8Qu7vxIxshni-P5GmqHbJIL2iauXYnv6giDdZ3SnjOBEEP_JFBisBU-p1yTmoupeZyekBUC_Icirer4sACsNUf9Yf2ALB9F1UK7Nrt3vLKr1JOeHJSexBzJOLcBPuHrwLHZak_iuMn4AyWI7w5PYVFL24yyClq9wkLeyxZsiWg-mGWb-z1BgIehyyRpJ0jDgbIppdZZrk-dA4iJq7KhmdgTP_QpomVLxL5M-XjFkre75vXrrydExcTmeMLng41k1FC5rfk5yWLZbdbKLStUivVSCIllWx89ofdWlfc51-LOfnXRHuEUqnZ6VoqUfR-EmjCi9eAVZE-3pzdzpnxRp66bv4-3THRpYzQG5V8DYuUci7W0IsAXETpGdlIeBwfDYC2B6lg3Iy9Kpq0J5WQ
###

POST {{ControllerWeb_HostAddress}}/brands
Content-Type: application/json

{
  "name":"Test"
}
###

GET {{ControllerWeb_HostAddress}}/brands/{{id}}
Accept: application/json
###

PUT {{ControllerWeb_HostAddress}}/brands/{{id}}
Content-Type: application/json

{
  "name":"Test2"
}
###

DELETE {{ControllerWeb_HostAddress}}/brands/{{id}}

###
